# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Maps and Legends
email: Jesse.Spielman@gmail.com
description: >-
  A collection of points of interest, museums, restaurants and bars worth visiting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maps-and-legends.heavyimage.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: heavyimage
github_username:  heavyimage
collections:
  locations:
    output: False

# leaflet
map_debug: False
leafletstyle: 'Hydda_Full'

home_lat: 40.78
home_lon: -73.96
home_zoom: 11

# Layers
layers:
  - name: "restaurants"
    icon: "utensils"
    color: "red"
    title: "Restaurants"
  - name: "bars"
    icon: "beer"
    color: "cadetblue"
    title: "Bars"
  - name: "pois"
    icon: "star"
    color: "darkpurple"
    title: "POIs"
  - name: "coffee"
    icon: "coffee"
    color: "black"
    title: "Coffee Shops"
  - name: "bagels"
    icon: "smile"
    color: "beige"
    title: "Bagels"
  - name: "parks"
    icon: "tree"
    color: "green"
    title: "Parks / Trails"
  - name: "museums"
    icon: "gem"
    color: "gray"
    title: "Museums"
  - name: "stores"
    icon: "dollar-sign"
    color: "purple"
    title: "Stores"
  - name: "dessert"
    icon: "birthday-cake"
    color: "pink"
    title: "Dessert"
  - name: "boardgamecafes"
    icon: "chess-rook"
    color: "orange"
    title: "Board Game Cafes"

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - screenshot.png
